import '../../../core/models/content_source_type.dart';
import '../../../core/models/lesson.dart';
import '../../../core/models/section.dart';

/// Match only the seeded Grade 4 lesson, whose ID is generated by Supabase.
bool isTypesOfFractionsLesson(Lesson lesson) =>
    lesson.sourceType == ContentSourceType.builtIn &&
    lesson.gradeLevel == GradeLevel.grade4 &&
    lesson.title.trim().replaceAll(RegExp(r'\s+'), ' ').toLowerCase() ==
        'types of fractions';

const List<String> fractionsPhases = <String>[
  'Parts',
  'Proper',
  'Improper',
  'Build mixed',
  'Identify',
  'Practice',
];

enum FractionActivityType { parts, proper, improper, build, identify }

enum FractionType { proper, improper, mixed }

class FractionActivitySpec {
  const FractionActivitySpec(
    this.type,
    this.numerator,
    this.denominator, {
    this.wholes = 0,
    this.initiallyHidden = false,
  });

  final FractionActivityType type;
  final int numerator;
  final int denominator;
  final int wholes;
  final bool initiallyHidden;

  String get label => '${wholes == 0 ? '' : '$wholes '}$numerator/$denominator';

  FractionType get writtenType =>
      wholes > 0
          ? FractionType.mixed
          : numerator < denominator
          ? FractionType.proper
          : FractionType.improper;

  int get totalParts => wholes * denominator + numerator;

  /// Each entry describes one equal-sized whole strip; no strip is overfilled.
  List<int> get shadedPartsByStrip {
    int remaining = totalParts;
    final List<int> strips = <int>[];
    while (remaining > 0) {
      final int shaded = remaining.clamp(0, denominator);
      strips.add(shaded);
      remaining -= shaded;
    }
    return strips;
  }
}

const List<List<FractionActivitySpec>> fractionsActivities =
    <List<FractionActivitySpec>>[
      <FractionActivitySpec>[
        FractionActivitySpec(FractionActivityType.parts, 3, 5),
      ],
      <FractionActivitySpec>[
        FractionActivitySpec(FractionActivityType.proper, 3, 5),
        FractionActivitySpec(FractionActivityType.proper, 2, 7),
        FractionActivitySpec(FractionActivityType.proper, 6, 9),
      ],
      <FractionActivitySpec>[
        FractionActivitySpec(FractionActivityType.improper, 7, 4),
        FractionActivitySpec(FractionActivityType.improper, 9, 5),
        FractionActivitySpec(FractionActivityType.improper, 6, 6),
      ],
      <FractionActivitySpec>[
        FractionActivitySpec(FractionActivityType.build, 3, 4, wholes: 1),
        FractionActivitySpec(FractionActivityType.build, 1, 3, wholes: 2),
        FractionActivitySpec(FractionActivityType.build, 2, 5, wholes: 3),
      ],
      <FractionActivitySpec>[
        FractionActivitySpec(FractionActivityType.identify, 4, 9),
        FractionActivitySpec(FractionActivityType.identify, 9, 4),
        FractionActivitySpec(FractionActivityType.identify, 1, 4, wholes: 2),
      ],
      <FractionActivitySpec>[
        FractionActivitySpec(FractionActivityType.identify, 3, 8),
        FractionActivitySpec(FractionActivityType.identify, 8, 3),
        FractionActivitySpec(
          FractionActivityType.identify,
          5,
          5,
          initiallyHidden: true,
        ),
        FractionActivitySpec(
          FractionActivityType.identify,
          2,
          3,
          wholes: 2,
          initiallyHidden: true,
        ),
      ],
    ];
