-- =============================================================================
-- Migration: 0022_grant_app_schema_usage_to_service_role.sql
--
-- BUG: student-login's Edge Function client connects as service_role and
-- calls public.verify_student_credentials (0020), which internally calls
-- app.verify_student_credentials (0017) with SECURITY INVOKER semantics —
-- so that inner call is itself checked against the CALLING role, which is
-- service_role here. 0017 already grants service_role EXECUTE on
-- app.verify_student_credentials specifically, but 0016 only grants USAGE
-- on the `app` schema itself to `authenticated`, never to `service_role`.
-- Schema USAGE and function EXECUTE are two separate, both-required
-- permission checks in Postgres — having one without the other still
-- fails with "permission denied for schema app" (42501), which is exactly
-- what was observed.
--
-- FIX: grant service_role the same schema-level USAGE authenticated
-- already has. This does not widen what service_role can call — it can
-- still only execute the one function (app.verify_student_credentials)
-- it was already explicitly granted EXECUTE on in 0017; this just lets
-- that existing grant actually take effect.
-- =============================================================================

grant usage on schema app to service_role;